import pandas as pd

movies = [
    (1, "The Godfather", "Crime|Drama", 1970, 9.2, "mafia|crime|family|classic"),
    (2, "Star Wars: A New Hope", "Action|Sci-Fi|Adventure", 1970, 8.6, "space|empire|jedi|war"),
    (3, "Alien", "Horror|Sci-Fi", 1970, 8.5, "alien|space|survival|horror"),
    (4, "The Shining", "Horror|Drama", 1980, 8.4, "ghosts|hotel|madness|stephen king"),
    (5, "Blade Runner", "Sci-Fi|Thriller", 1980, 8.1, "robots|dystopia|future|cyberpunk"),
    (6, "Terminator", "Action|Sci-Fi", 1980, 8.1, "robots|future|time travel|war"),
    (7, "Back to the Future", "Adventure|Comedy|Sci-Fi", 1980, 8.5, "time travel|high school|car|80s"),
    (8, "E.T. the Extra-Terrestrial", "Family|Sci-Fi", 1980, 7.9, "alien|friendship|kids|classic"),
    (9, "The Empire Strikes Back", "Action|Adventure|Sci-Fi", 1980, 8.7, "space|jedi|father|war"),
    (10, "Raiders of the Lost Ark", "Action|Adventure", 1980, 8.4, "treasure|nazis|archaeology"),
    (11, "Die Hard", "Action|Thriller", 1980, 8.2, "christmas|police|terrorist|skyscraper"),
    (12, "Full Metal Jacket", "Drama|War", 1980, 8.3, "vietnam|army|training|war"),
    (13, "Scarface", "Crime|Drama", 1980, 8.3, "drugs|miami|gangster|crime"),
    (14, "Ghostbusters", "Comedy|Fantasy", 1980, 7.8, "ghosts|new york|funny|team"),
    (15, "The Breakfast Club", "Comedy|Drama", 1980, 7.8, "high school|teen|detention"),
    (16, "Robocop", "Action|Sci-Fi", 1980, 7.6, "police|robots|cyborg|dystopia"),
    (17, "Top Gun", "Action|Drama", 1980, 6.9, "planes|pilots|military|80s"),
    (18, "Akira", "Animation|Sci-Fi", 1980, 8.0, "anime|tokyo|cyberpunk|motorcycle"),
    (19, "Cinema Paradiso", "Drama|Romance", 1980, 8.5, "movies|childhood|italy|nostalgia"),
    (20, "Beetlejuice", "Comedy|Fantasy", 1980, 7.5, "ghosts|afterlife|tim burton"),
    (21, "Pulp Fiction", "Crime|Drama", 1990, 8.9, "gangster|violence|tarantino|cool"),
    (22, "The Matrix", "Action|Sci-Fi", 1990, 8.7, "simulation|robots|kung fu|future"),
    (23, "Forrest Gump", "Drama|Romance", 1990, 8.8, "history|life|running|love"),
    (24, "The Lion King", "Animation|Drama", 1990, 8.5, "africa|animals|king|disney"),
    (25, "Fight Club", "Drama", 1990, 8.8, "psychology|fighting|anarchy|twist"),
    (26, "Jurassic Park", "Adventure|Sci-Fi", 1990, 8.2, "dinosaurs|park|survival|nature"),
    (27, "Titanic", "Drama|Romance", 1990, 7.9, "ship|love|disaster|history"),
    (28, "Toy Story", "Animation|Comedy", 1990, 8.3, "toys|friendship|pixar|kids"),
    (29, "The Silence of the Lambs", "Crime|Thriller", 1990, 8.6, "serial killer|fbi|psychopath"),
    (30, "Schindler's List", "Biography|Drama", 1990, 9.0, "ww2|holocaust|history|black and white"),
    (31, "Goodfellas", "Biography|Crime", 1990, 8.7, "mafia|gangster|new york"),
    (32, "Saving Private Ryan", "Drama|War", 1990, 8.6, "ww2|soldiers|mission|normandy"),
    (33, "Terminator 2: Judgment Day", "Action|Sci-Fi", 1990, 8.6, "robots|time travel|protector|action"),
    (34, "The Sixth Sense", "Drama|Thriller", 1990, 8.2, "ghosts|twist|psychology|child"),
    (35, "The Truman Show", "Comedy|Drama", 1990, 8.2, "reality tv|simulation|media|life"),
    (36, "Se7en", "Crime|Thriller", 1990, 8.6, "detective|serial killer|sins"),
    (37, "Home Alone", "Comedy|Family", 1990, 7.7, "christmas|thieves|kids|house"),
    (38, "Men in Black", "Action|Comedy|Sci-Fi", 1990, 7.3, "aliens|agents|secret|funny"),
    (39, "Scream", "Horror|Mystery", 1990, 7.4, "slasher|teen|killer|meta"),
    (40, "Trainspotting", "Drama", 1990, 8.1, "drugs|addiction|scotland|youth"),
    (41, "The Dark Knight", "Action|Crime|Drama", 2000, 9.0, "batman|joker|superhero|dark"),
    (42, "The Lord of the Rings: The Fellowship of the Ring", "Adventure|Fantasy", 2000, 8.8, "magic|elves|journey|ring"),
    (43, "Harry Potter and the Sorcerer's Stone", "Adventure|Fantasy", 2000, 7.6, "magic|school|wizards|kids"),
    (44, "Spirited Away", "Animation|Adventure", 2000, 8.6, "anime|spirits|magic|ghibli"),
    (45, "Avatar", "Action|Adventure|Sci-Fi", 2000, 7.8, "aliens|planet|3d|war"),
    (46, "Gladiator", "Action|Drama", 2000, 8.5, "rome|revenge|sword|history"),
    (47, "Shrek", "Animation|Comedy", 2000, 7.9, "ogre|fairy tale|funny|donkey"),
    (48, "Finding Nemo", "Animation|Adventure", 2000, 8.2, "fish|ocean|pixar|family"),
    (49, "The Prestige", "Drama|Mystery", 2000, 8.5, "magic|rivalry|twist|illusion"),
    (50, "Eternal Sunshine of the Spotless Mind", "Drama|Romance|Sci-Fi", 2000, 8.3, "memory|love|breakup|surreal"),
    (51, "Iron Man", "Action|Sci-Fi", 2000, 7.9, "marvel|superhero|tech|robot"),
    (52, "No Country for Old Men", "Crime|Drama", 2000, 8.2, "texas|killer|chase|western"),
    (53, "Wall-E", "Animation|Sci-Fi", 2000, 8.4, "robot|space|love|environment"),
    (54, "Inglourious Basterds", "Adventure|Drama|War", 2000, 8.3, "nazis|ww2|tarantino|revenge"),
    (55, "Up", "Animation|Adventure", 2000, 8.3, "balloons|old man|flying|pixar"),
    (56, "Donnie Darko", "Drama|Sci-Fi", 2000, 8.0, "time travel|rabbit|teen|dark"),
    (57, "Kill Bill: Vol. 1", "Action|Crime", 2000, 8.2, "revenge|sword|martial arts|tarantino"),
    (58, "Pan's Labyrinth", "Drama|Fantasy", 2000, 8.2, "war|fantasy|monster|spain"),
    (59, "Slumdog Millionaire", "Drama|Romance", 2000, 8.0, "india|game show|destiny|love"),
    (60, "Mean Girls", "Comedy", 2000, 7.1, "high school|teen|girls|funny"),
    (61, "Inception", "Action|Sci-Fi", 2010, 8.8, "dreams|heist|mind|nolan"),
    (62, "Interstellar", "Adventure|Sci-Fi", 2010, 8.7, "space|black hole|time|family"),
    (63, "Avengers: Endgame", "Action|Sci-Fi", 2010, 8.4, "superhero|marvel|thanos|battle"),
    (64, "Parasite", "Drama|Thriller", 2010, 8.5, "class|korea|house|twist"),
    (65, "Joker", "Crime|Drama", 2010, 8.4, "clown|madness|society|dark"),
    (66, "Whiplash", "Drama|Music", 2010, 8.5, "drums|jazz|obsession|teacher"),
    (67, "Coco", "Animation|Family", 2010, 8.4, "mexico|music|death|family"),
    (68, "Mad Max: Fury Road", "Action|Adventure", 2010, 8.1, "cars|desert|chase|apocalypse"),
    (69, "Get Out", "Horror|Mystery", 2010, 7.8, "racism|hypnosis|thriller|mind"),
    (70, "The Wolf of Wall Street", "Biography|Comedy", 2010, 8.2, "money|stock|excess|crime"),
    (71, "La La Land", "Drama|Music|Romance", 2010, 8.0, "musical|hollywood|love|jazz"),
    (72, "Spider-Man: Into the Spider-Verse", "Animation|Action", 2010, 8.4, "spider-man|multiverse|comic|style"),
    (73, "Django Unchained", "Drama|Western", 2010, 8.5, "slavery|bounty hunter|revenge|tarantino"),
    (74, "Gone Girl", "Drama|Mystery", 2010, 8.1, "missing|marriage|twist|thriller"),
    (75, "Her", "Drama|Romance|Sci-Fi", 2010, 8.0, "ai|love|future|loneliness"),
    (76, "Black Panther", "Action|Sci-Fi", 2010, 7.3, "marvel|wakanda|king|superhero"),
    (77, "Arrival", "Drama|Sci-Fi", 2010, 7.9, "aliens|language|time|communication"),
    (78, "Frozen", "Animation|Adventure", 2010, 7.4, "princess|snow|sisters|musical"),
    (79, "Knives Out", "Comedy|Crime", 2010, 7.9, "detective|murder|whodunit|family"),
    (80, "Ex Machina", "Drama|Sci-Fi", 2010, 7.7, "robot|ai|turing test|thriller"),
    (81, "Dune", "Action|Adventure|Sci-Fi", 2020, 8.0, "sand|space|empire|spice"),
    (82, "Oppenheimer", "Biography|Drama", 2020, 8.4, "bomb|science|ww2|politics"),
    (83, "Barbie", "Adventure|Comedy", 2020, 7.0, "doll|pink|society|meta"),
    (84, "The Batman", "Action|Crime", 2020, 7.8, "detective|dark|gotham|rain"),
    (85, "Everything Everywhere All At Once", "Action|Adventure", 2020, 7.8, "multiverse|family|kung fu|chaos"),
    (86, "Top Gun: Maverick", "Action|Drama", 2020, 8.3, "planes|pilots|sequel|action"),
    (87, "Spider-Man: No Way Home", "Action|Sci-Fi", 2020, 8.2, "multiverse|spiderman|marvel|teamup"),
    (88, "Avatar: The Way of Water", "Action|Adventure", 2020, 7.6, "ocean|family|aliens|3d"),
    (89, "Puss in Boots: The Last Wish", "Animation|Adventure", 2020, 7.9, "cat|death|fairy tale|action"),
    (90, "The Whale", "Drama", 2020, 7.7, "obesity|family|sad|redemption"),
    (91, "Soul", "Animation|Adventure", 2020, 8.0, "jazz|life|soul|pixar"),
    (92, "Tenet", "Action|Sci-Fi", 2020, 7.3, "time|entropy|spy|complex"),
    (93, "A Quiet Place Part II", "Drama|Horror", 2020, 7.2, "monsters|silence|family|survival"),
    (94, "Encanto", "Animation|Family", 2020, 7.2, "magic|colombia|family|musical"),
    (95, "No Time to Die", "Action|Adventure", 2020, 7.3, "bond|spy|action|finale"),
    (96, "Black Widow", "Action|Sci-Fi", 2020, 6.7, "marvel|spy|family|action"),
    (97, "Elvis", "Biography|Drama", 2020, 7.3, "music|rock|king|biopic"),
    (98, "Bullet Train", "Action|Comedy", 2020, 7.3, "train|assassins|fast|funny"),
    (99, "Triangle of Sadness", "Comedy|Drama", 2020, 7.3, "cruise|rich|satire|social"),
    (100, "Poor Things", "Comedy|Romance|Sci-Fi", 2020, 8.0, "frankenstein|feminism|weird|surreal")
]

df_movies = pd.DataFrame(movies, columns=['id', 'title', 'genres', 'decade', 'vote_average', 'keywords'])
df_movies.to_csv('movies_dataset.csv', index=False)

print(f"Dataset actualizado con 100 películas reales.")